// Site content map. Add a topic here first (status: "planned"), then flip it
// to "published" once topics/<slug>.html exists and is written.
//
// tag: short layer label used as the visual/legend code for the module.

const SITE_DATA = [
  {
    id: "fundamentals",
    number: "01",
    tag: "FUND",
    title: "Networking Fundamentals",
    blurb: "The building blocks everything else stacks on top of.",
    topics: [
      { title: "OSI Model vs TCP/IP Model", slug: "osi-vs-tcpip", status: "published" },
      { title: "Network Topologies", slug: "network-topologies", status: "published" },
      { title: "Collision Domain vs Broadcast Domain", slug: "broadcast-vs-collision-domain", status: "published" },
      { title: "Hubs vs Switches vs Routers", slug: "hubs-switches-routers", status: "published" },
      { title: "Duplex: Half vs Full", slug: "duplex", status: "published" },
    ],
  },
  {
    id: "layer2",
    number: "02",
    tag: "L2",
    title: "Layer 2 — Data Link",
    blurb: "Frames, MAC addresses, and how switches keep loops from eating the network.",
    topics: [
      { title: "Ethernet Frame & MAC Addressing", slug: "ethernet-frame-mac", status: "published" },
      { title: "ARP", slug: "arp", status: "published" },
      { title: "VLANs & 802.1Q Trunking", slug: "vlans-trunking", status: "published" },
      { title: "Native VLAN & VLAN Hopping", slug: "native-vlan-hopping", status: "published" },
      { title: "Spanning Tree Protocol (802.1D)", slug: "stp-8021d", status: "published" },
      { title: "RSTP & MST", slug: "rstp-mst", status: "published" },
      { title: "EtherChannel / Link Aggregation", slug: "etherchannel", status: "published" },
      { title: "Switch Port Security", slug: "port-security", status: "published" },
    ],
  },
  {
    id: "layer3",
    number: "03",
    tag: "L3",
    title: "Layer 3 — Network",
    blurb: "Addressing, routing tables, and how a packet actually gets somewhere else.",
    topics: [
      { title: "IPv4 Addressing, CIDR & VLSM", slug: "ipv4-subnetting-cidr-vlsm", status: "published" },
      { title: "IPv4 Header Structure", slug: "ipv4-header", status: "published" },
      { title: "IPv6 Addressing & Header Basics", slug: "ipv6-basics", status: "published" },
      { title: "IPv4 Fragmentation", slug: "ipv4-fragmentation", status: "published" },
      { title: "ICMP — Ping & Traceroute Mechanics", slug: "icmp", status: "published" },
      { title: "Routing Tables & Longest Prefix Match", slug: "routing-tables-lpm", status: "published" },
      { title: "Administrative Distance & Metrics", slug: "admin-distance-metrics", status: "published" },
      { title: "Static Routing", slug: "static-routing", status: "published" },
      { title: "Distance-Vector Routing (RIP, EIGRP)", slug: "distance-vector-rip-eigrp", status: "published" },
      { title: "Link-State Routing (OSPF, IS-IS)", slug: "link-state-ospf-isis", status: "published" },
      { title: "BGP Basics", slug: "bgp-basics", status: "published" },
      { title: "NAT & PAT", slug: "nat-pat", status: "published" },
      { title: "Inter-VLAN Routing", slug: "inter-vlan-routing", status: "published" },
      { title: "Packet Flow Across Networks", slug: "packet-flow", status: "published" },
    ],
  },
  {
    id: "layer4",
    number: "04",
    tag: "L4",
    title: "Layer 4 — Transport",
    blurb: "TCP reliability mechanics and the UDP alternative.",
    topics: [
      { title: "TCP Header Structure", slug: "tcp-header", status: "planned" },
      { title: "TCP 3-Way Handshake & Termination", slug: "tcp-handshake-termination", status: "planned" },
      { title: "Flow Control & Congestion Control", slug: "flow-congestion-control", status: "planned" },
      { title: "UDP Header & Use Cases", slug: "udp-header", status: "planned" },
      { title: "Ports & Sockets", slug: "ports-sockets", status: "planned" },
    ],
  },
  {
    id: "app-naming",
    number: "05",
    tag: "APP",
    title: "Application Layer & Name Resolution",
    blurb: "Where names become addresses and requests become pages.",
    topics: [
      { title: "DNS Hierarchy & Record Types", slug: "dns-hierarchy-records", status: "planned" },
      { title: "DNS Resolution Flow", slug: "dns-resolution-flow", status: "planned" },
      { title: "DHCP Process (DORA)", slug: "dhcp-dora", status: "planned" },
      { title: "HTTP/HTTPS — 1.1 vs 2 vs 3", slug: "http-https-versions", status: "planned" },
      { title: "Capstone: What Happens When You Type a URL", slug: "url-to-page-capstone", status: "planned" },
    ],
  },
  {
    id: "security",
    number: "06",
    tag: "SEC",
    title: "Security & Encryption",
    blurb: "Keeping traffic private, authenticated, and out of the wrong hands.",
    topics: [
      { title: "Symmetric vs Asymmetric Encryption", slug: "symmetric-vs-asymmetric", status: "planned" },
      { title: "PKI & Digital Certificates", slug: "pki-certificates", status: "planned" },
      { title: "TLS/SSL Handshake (1.2 vs 1.3)", slug: "tls-handshake", status: "planned" },
      { title: "IPsec Fundamentals (AH vs ESP)", slug: "ipsec-fundamentals", status: "planned" },
      { title: "IKEv1 vs IKEv2", slug: "ikev1-vs-ikev2", status: "planned" },
      { title: "VPN Types", slug: "vpn-types", status: "planned" },
      { title: "Firewalls & ACLs", slug: "firewalls-acls", status: "planned" },
      { title: "Common Attacks: ARP Spoofing, MITM, DDoS", slug: "common-attacks", status: "planned" },
    ],
  },
];
