// Site content map. Add a topic here first (status: "planned"), then flip it
// to "published" once topics/<slug>.html exists and is written.
//
// tag: short layer label used as the visual/legend code for the module.

const SITE_DATA = [
  {
    id: "fundamentals",
    track: "networking",
    path: "topics",
    color: "fund",
    number: "01",
    tag: "FUND",
    title: "Networking Fundamentals",
    blurb: "The building blocks everything else stacks on top of.",
    topics: [
      { title: "OSI Model vs TCP/IP Model", slug: "osi-vs-tcpip", status: "published", level: "beginner", summary: "Map seven OSI layers to the TCP/IP stack and follow encapsulation.", aliases: ["Open Systems Interconnection", "layers", "encapsulation"] },
      { title: "Network Topologies", slug: "network-topologies", status: "published", level: "beginner", summary: "Compare star, bus, ring, and mesh layouts and their failure points." },
      { title: "Collision Domain vs Broadcast Domain", slug: "broadcast-vs-collision-domain", status: "published", level: "beginner", summary: "See where collisions and broadcasts stop at switches and routers." },
      { title: "Hubs vs Switches vs Routers", slug: "hubs-switches-routers", status: "published", level: "beginner", summary: "Separate flooding, MAC-based switching, and IP routing." },
      { title: "Duplex: Half vs Full", slug: "duplex", status: "published", level: "beginner", summary: "Understand simultaneous transmission, shared media, and duplex mismatches." },
      { title: "Copper, Fiber, Transceivers & PoE", slug: "copper-fiber-transceivers-poe", status: "published", level: "beginner", summary: "Match media, optics, distance, and power requirements, then calculate a PoE budget.", aliases: ["physical layer", "cabling", "Cat6A", "SFP", "DAC", "Power over Ethernet", "PSE", "PD"], prerequisites: ["networking:osi-vs-tcpip"], related: ["networking:ethernet-frame-mac", "networking:bandwidth-throughput-latency", "networking:etherchannel"] },
      { title: "Bandwidth, Throughput, Latency, Jitter & Loss", slug: "bandwidth-throughput-latency", status: "published", level: "beginner", summary: "Separate capacity from application speed and work through transfer time and TCP window limits.", aliases: ["performance", "goodput", "RTT", "bandwidth delay product", "BDP", "packet loss"], prerequisites: ["networking:osi-vs-tcpip", "networking:duplex"], related: ["networking:flow-congestion-control", "networking:icmp", "networking:network-troubleshooting-tools"] },
    ],
  },
  {
    id: "layer2",
    track: "networking",
    path: "topics",
    color: "l2",
    number: "02",
    tag: "L2",
    title: "Layer 2: Data Link",
    blurb: "Frames, MAC addresses, and how switches keep loops from eating the network.",
    topics: [
      { title: "Ethernet Frame & MAC Addressing", slug: "ethernet-frame-mac", status: "published", level: "beginner", summary: "Read Ethernet fields, MAC addresses, EtherType, and the frame check sequence." },
      { title: "ARP", slug: "arp", status: "published", level: "beginner", summary: "Resolve an on-link IPv4 next hop to its MAC address and inspect the cache.", aliases: ["Address Resolution Protocol", "neighbor cache"], prerequisites: ["networking:ethernet-frame-mac", "networking:ipv4-subnetting-cidr-vlsm"], related: ["networking:dhcp-dora", "networking:packet-flow"] },
      { title: "VLANs & 802.1Q Trunking", slug: "vlans-trunking", status: "published", level: "intermediate", summary: "Divide broadcast domains and carry VLAN tags across a trunk.", aliases: ["virtual LAN", "dot1q"] },
      { title: "Native VLAN & VLAN Hopping", slug: "native-vlan-hopping", status: "published", level: "intermediate", summary: "Understand untagged trunk traffic and double-tagging risks." },
      { title: "Spanning Tree Protocol (802.1D)", slug: "stp-8021d", status: "published", level: "intermediate", summary: "Follow root election, port roles, and loop prevention.", aliases: ["STP", "BPDU"] },
      { title: "RSTP & MST", slug: "rstp-mst", status: "published", level: "intermediate", summary: "Compare rapid convergence with multiple spanning-tree instances.", aliases: ["Rapid Spanning Tree", "Multiple Spanning Tree"] },
      { title: "EtherChannel / Link Aggregation", slug: "etherchannel", status: "published", level: "intermediate", summary: "Bundle links with LACP and understand per-flow load distribution.", aliases: ["LACP", "port channel", "LAG"] },
      { title: "Switch Port Security", slug: "port-security", status: "published", level: "intermediate", summary: "Limit learned MAC addresses and distinguish violation actions." },
    ],
  },
  {
    id: "layer3",
    track: "networking",
    path: "topics",
    color: "l3",
    number: "03",
    tag: "L3",
    title: "Layer 3: Network",
    blurb: "Addressing, routing tables, and how a packet actually gets somewhere else.",
    topics: [
      { title: "IPv4 Addressing, CIDR & VLSM", slug: "ipv4-subnetting-cidr-vlsm", status: "published", level: "beginner", summary: "Calculate subnet boundaries, usable ranges, and a worked VLSM allocation.", aliases: ["subnetting", "subnet mask", "Classless Inter-Domain Routing", "Variable Length Subnet Masking"], prerequisites: ["networking:osi-vs-tcpip", "networking:hubs-switches-routers"], related: ["networking:routing-tables-lpm", "networking:arp", "networking:inter-vlan-routing"] },
      { title: "IPv4 Header Structure", slug: "ipv4-header", status: "published", level: "intermediate", summary: "Inspect TTL, protocol, fragmentation flags, and header checksum." },
      { title: "IPv6 Addressing & Header Basics", slug: "ipv6-basics", status: "published", level: "beginner", summary: "Read IPv6 notation, address scopes, and the fixed base header." },
      { title: "IPv4 Fragmentation", slug: "ipv4-fragmentation", status: "published", level: "intermediate", summary: "Trace MTU limits, fragment offsets, and destination reassembly.", aliases: ["MTU", "maximum transmission unit", "PMTUD"] },
      { title: "ICMP: Ping & Traceroute Mechanics", slug: "icmp", status: "published", level: "beginner", summary: "Interpret echo replies, TTL expiry, and unreachable messages.", aliases: ["Internet Control Message Protocol", "tracert"] },
      { title: "Routing Tables & Longest Prefix Match", slug: "routing-tables-lpm", status: "published", level: "intermediate", summary: "Choose the most specific matching route before forwarding.", aliases: ["LPM", "default route"] },
      { title: "Administrative Distance & Metrics", slug: "admin-distance-metrics", status: "published", level: "intermediate", summary: "Separate route-source preference from a protocol's path metric." },
      { title: "Static Routing", slug: "static-routing", status: "published", level: "beginner", summary: "Use next-hop, default, and floating static routes." },
      { title: "Distance-Vector Routing (RIP, EIGRP)", slug: "distance-vector-rip-eigrp", status: "published", level: "intermediate", summary: "Compare neighbor-based route learning, metrics, and convergence." },
      { title: "Link-State Routing (OSPF, IS-IS)", slug: "link-state-ospf-isis", status: "published", level: "intermediate", summary: "Build a topology database and calculate shortest paths across areas." },
      { title: "BGP Basics", slug: "bgp-basics", status: "published", level: "intermediate", summary: "Trace BGP sessions, next hops, two-provider path selection, and routing safeguards.", aliases: ["Border Gateway Protocol", "AS path", "eBGP", "iBGP", "LOCAL_PREF", "NEXT_HOP", "next-hop-self", "route reflector", "RPKI", "ROA"], prerequisites: ["networking:routing-tables-lpm", "networking:admin-distance-metrics", "networking:tcp-handshake-termination"], related: ["networking:link-state-ospf-isis", "networking:network-troubleshooting-tools", "networking:packet-capture-wireshark-tcpdump"] },
      { title: "NAT & PAT", slug: "nat-pat", status: "published", level: "intermediate", summary: "Follow address and port translations through a state table.", aliases: ["Network Address Translation", "Port Address Translation", "SNAT", "DNAT", "source NAT", "destination NAT", "NAT overload"] },
      { title: "Inter-VLAN Routing", slug: "inter-vlan-routing", status: "published", level: "intermediate", summary: "Route between VLANs with subinterfaces or switched virtual interfaces.", aliases: ["SVI", "router on a stick"] },
      { title: "Packet Flow Across Networks", slug: "packet-flow", status: "published", level: "intermediate", summary: "Track changing Ethernet headers and routed IP packets hop by hop." },
    ],
  },
  {
    id: "layer4",
    track: "networking",
    path: "topics",
    color: "l4",
    number: "04",
    tag: "L4",
    title: "Layer 4: Transport",
    blurb: "TCP reliability mechanics and the UDP alternative.",
    topics: [
      { title: "TCP Header Structure", slug: "tcp-header", status: "published", level: "intermediate", summary: "Decode sequence numbers, acknowledgments, flags, and window fields." },
      { title: "TCP 3-Way Handshake & Termination", slug: "tcp-handshake-termination", status: "published", level: "beginner", summary: "Follow SYN, SYN-ACK, ACK, FIN, and connection state changes." },
      { title: "Flow Control & Congestion Control", slug: "flow-congestion-control", status: "published", level: "intermediate", summary: "Separate receiver capacity from network capacity using rwnd and cwnd.", aliases: ["TCP", "receive window", "congestion window", "slow start"], prerequisites: ["networking:tcp-header", "networking:tcp-handshake-termination"], related: ["networking:ipv4-fragmentation", "networking:http-https-versions"] },
      { title: "UDP Header & Use Cases", slug: "udp-header", status: "published", level: "beginner", summary: "Read UDP's four fields and understand what delivery it does not guarantee." },
      { title: "Ports & Sockets", slug: "ports-sockets", status: "published", level: "beginner", summary: "Distinguish service ports, ephemeral ports, and connection endpoints." },
    ],
  },
  {
    id: "app-naming",
    track: "networking",
    path: "topics",
    color: "app",
    number: "05",
    tag: "APP",
    title: "Application Layer & Name Resolution",
    blurb: "Where names become addresses and requests become pages.",
    topics: [
      { title: "DNS Hierarchy & Record Types", slug: "dns-hierarchy-records", status: "published", level: "beginner", summary: "Navigate zones, delegation, and A, AAAA, CNAME, MX, and TXT records.", aliases: ["Domain Name System"] },
      { title: "DNS Resolution Flow", slug: "dns-resolution-flow", status: "published", level: "beginner", summary: "Follow a lookup from stub resolver through cache, root, TLD, and authority.", aliases: ["Domain Name System", "recursive resolver", "name lookup"], prerequisites: ["networking:dns-hierarchy-records"], related: ["networking:dhcp-dora", "networking:url-to-page-capstone"] },
      { title: "DHCP Process (DORA)", slug: "dhcp-dora", status: "published", level: "beginner", summary: "Trace address leasing through Discover, Offer, Request, and ACK.", aliases: ["Dynamic Host Configuration Protocol"] },
      { title: "HTTP/HTTPS: 1.1 vs 2 vs 3", slug: "http-https-versions", status: "published", level: "intermediate", summary: "Compare HTTP multiplexing, TCP ordering, and QUIC stream delivery.", aliases: ["QUIC", "HTTP/3", "HTTP/2", "head of line blocking"] },
      { title: "Capstone: What Happens When You Type a URL", slug: "url-to-page-capstone", status: "published", level: "intermediate", summary: "Connect DNS, ARP, routing, TCP, TLS, and HTTP in one page load." },
    ],
  },
  {
    id: "security",
    track: "networking",
    path: "topics",
    color: "sec",
    number: "06",
    tag: "SEC",
    title: "Security & Encryption",
    blurb: "Keeping traffic private, authenticated, and out of the wrong hands.",
    topics: [
      { title: "Symmetric vs Asymmetric Encryption", slug: "symmetric-vs-asymmetric", status: "published", level: "beginner", summary: "Separate shared-key encryption, public-key operations, and hybrid protocols." },
      { title: "PKI & Digital Certificates", slug: "pki-certificates", status: "published", level: "intermediate", summary: "Verify identities through certificate chains, trust stores, and revocation.", aliases: ["Public Key Infrastructure", "X.509", "OCSP", "CRL"] },
      { title: "TLS/SSL Handshake (1.2 vs 1.3)", slug: "tls-handshake", status: "published", level: "intermediate", summary: "Compare handshake messages, certificate authentication, and key agreement.", aliases: ["Transport Layer Security", "HTTPS certificate"], prerequisites: ["networking:symmetric-vs-asymmetric", "networking:pki-certificates"], related: ["networking:tcp-handshake-termination", "networking:http-https-versions"] },
      { title: "IPsec Fundamentals (AH vs ESP)", slug: "ipsec-fundamentals", status: "published", level: "intermediate", summary: "Compare IPsec protection, transport mode, and tunnel mode." },
      { title: "IKEv1 vs IKEv2", slug: "ikev1-vs-ikev2", status: "published", level: "intermediate", summary: "Follow security association negotiation and key exchange.", aliases: ["Internet Key Exchange"] },
      { title: "VPN Types", slug: "vpn-types", status: "published", level: "beginner", summary: "Distinguish remote-access and site-to-site encrypted connections.", aliases: ["Virtual Private Network"] },
      { title: "Firewalls & ACLs", slug: "firewalls-acls", status: "published", level: "intermediate", summary: "Compare packet filters, stateful inspection, and rule ordering.", aliases: ["Access Control List"] },
      { title: "Common Attacks: ARP Spoofing, MITM, DDoS", slug: "common-attacks", status: "published", level: "intermediate", summary: "Connect common network threats with protocol weaknesses and defenses." },
    ],
  },
  {
    id: "wireless",
    track: "networking",
    path: "topics",
    color: "wifi",
    number: "07",
    tag: "WLAN",
    title: "Wireless Networking",
    blurb: "Shared airtime, secure joins, and the handoff between access points.",
    topics: [
      { title: "Wi-Fi Bands, Channels & Airtime", slug: "wifi-bands-channels-airtime", status: "published", level: "beginner", summary: "Compare 2.4, 5, and 6 GHz, channel width, contention, and signal measurements.", aliases: ["WiFi", "WLAN", "802.11", "Wi-Fi 6E", "Wi-Fi 7", "RSSI", "SNR", "OFDMA", "CSMA/CA"], prerequisites: ["networking:duplex", "networking:bandwidth-throughput-latency"], related: ["networking:wifi-association-security-roaming", "networking:copper-fiber-transceivers-poe"] },
      { title: "Wi-Fi Association, Security & Roaming", slug: "wifi-association-security-roaming", status: "published", level: "intermediate", summary: "Follow association and key establishment, then distinguish 802.11k, v, and r during roaming.", aliases: ["WiFi", "SSID", "BSSID", "WPA2", "WPA3", "SAE", "PMF", "802.1X", "EAP-TLS", "RADIUS", "OWE", "802.11r", "fast transition"], prerequisites: ["networking:wifi-bands-channels-airtime", "networking:symmetric-vs-asymmetric"], related: ["networking:dhcp-dora", "networking:pki-certificates", "networking:campus-design-segmentation"] },
    ],
  },
  {
    id: "enterprise",
    track: "networking",
    path: "topics",
    color: "enterprise",
    number: "08",
    tag: "ENT",
    title: "Enterprise Networking",
    blurb: "Practical campus structure, enforced boundaries, and resilient gateways.",
    topics: [
      { title: "Campus Design & Network Segmentation", slug: "campus-design-segmentation", status: "published", level: "intermediate", summary: "Choose access, distribution, and core roles and build an explicit communication policy.", aliases: ["collapsed core", "routed access", "guest isolation", "management VLAN", "failure domains"], prerequisites: ["networking:vlans-trunking", "networking:inter-vlan-routing", "networking:firewalls-acls"], related: ["networking:gateway-redundancy-vrrp-hsrp", "networking:rstp-mst", "networking:etherchannel"] },
      { title: "Default Gateway Redundancy: VRRP & HSRP", slug: "gateway-redundancy-vrrp-hsrp", status: "published", level: "intermediate", summary: "Follow virtual IP/MAC takeover, priority, preemption, tracking, and failover limits.", aliases: ["FHRP", "first hop redundancy protocol", "virtual router", "active standby", "RFC 9568"], prerequisites: ["networking:arp", "networking:routing-tables-lpm", "networking:campus-design-segmentation"], related: ["networking:link-state-ospf-isis", "networking:nat-pat", "networking:network-troubleshooting-tools"] },
    ],
  },
  {
    id: "operations",
    track: "networking",
    path: "topics",
    color: "ops",
    number: "09",
    tag: "OPS",
    title: "Operations & Troubleshooting",
    blurb: "Choose a useful test, capture the right evidence, and explain what it proves.",
    topics: [
      { title: "Network Troubleshooting & Diagnostic Tools", slug: "network-troubleshooting-tools", status: "published", level: "intermediate", summary: "Use bounded Windows and Linux checks to separate link, route, DNS, TCP, TLS, and application failures.", aliases: ["ping", "traceroute", "tracert", "Resolve-DnsName", "dig", "Test-NetConnection", "curl", "ip route", "ss"], prerequisites: ["networking:arp", "networking:icmp", "networking:dns-resolution-flow", "networking:tcp-handshake-termination"], related: ["networking:packet-capture-wireshark-tcpdump", "networking:ipv4-fragmentation", "networking:url-to-page-capstone"] },
      { title: "Packet Capture: Wireshark & tcpdump", slug: "packet-capture-wireshark-tcpdump", status: "published", level: "intermediate", summary: "Choose a capture point and filters, read a synthetic SYN trace, and recognize capture artifacts.", aliases: ["pcap", "pcapng", "BPF", "display filter", "capture filter", "SPAN", "TAP", "offload"], prerequisites: ["networking:network-troubleshooting-tools", "networking:tcp-header"], related: ["networking:tcp-handshake-termination", "networking:flow-congestion-control", "networking:tls-handshake"] },
    ],
  },
  {
    id: "ai-foundations",
    track: "ai",
    path: "ai/topics",
    color: "ai-fund",
    number: "01",
    tag: "LLM",
    title: "AI Foundations",
    blurb: "Separate the model from the application, then make its input and output checkable.",
    topics: [
      { title: "AI & LLM Foundations", slug: "ai-llm-foundations", status: "published", level: "beginner", summary: "Distinguish AI, ML, training, inference, model weights, runtimes, and chat applications.", aliases: ["generative AI", "machine learning", "transformer", "hallucination", "checkpoint"], prerequisites: [], related: ["ai:tokens-context-prompting", "ai:local-ai-hardware", "ai:rag-explained"] },
      { title: "Tokens, Context & Prompting", slug: "tokens-context-prompting", status: "published", level: "beginner", summary: "Budget context, separate instructions from evidence, and evaluate prompts against an answer key.", aliases: ["tokenizer", "BPE", "context window", "temperature", "few-shot", "prompt injection", "structured output"], prerequisites: ["ai:ai-llm-foundations"], related: ["ai:local-ai-hardware", "ai:run-first-local-model", "ai:rag-explained"] },
    ],
  },
  {
    id: "ai-local",
    track: "ai",
    path: "ai/topics",
    color: "ai-local",
    number: "02",
    tag: "LOCAL",
    title: "Local Inference",
    blurb: "Plan memory honestly, run one local request, and identify what each check proves.",
    topics: [
      { title: "Local AI Hardware", slug: "local-ai-hardware", status: "published", level: "beginner", summary: "Estimate weight and KV-cache memory, understand quantization, and separate fitting from speed.", aliases: ["RAM", "VRAM", "unified memory", "GPU", "CPU", "GGUF", "GQA", "quantization", "KV cache", "prefill", "decode"], prerequisites: ["ai:ai-llm-foundations", "ai:tokens-context-prompting"], related: ["ai:run-first-local-model", "ai:rag-explained"] },
      { title: "Run Your First Local Model", slug: "run-first-local-model", status: "published", level: "beginner", summary: "Use Ollama and PowerShell on Windows with a small model, explicit limits, and loopback-only access.", aliases: ["Ollama", "Windows", "PowerShell", "Qwen", "qwen2.5", "11434", "local LLM"], prerequisites: ["ai:local-ai-hardware", "ai:tokens-context-prompting"], related: ["ai:rag-explained", "networking:ports-sockets"] },
    ],
  },
  {
    id: "ai-retrieval",
    track: "ai",
    path: "ai/topics",
    color: "ai-rag",
    number: "03",
    tag: "RAG",
    title: "Retrieval & Grounding",
    blurb: "Select relevant, authorized evidence and check that the answer follows from it.",
    topics: [
      { title: "RAG Explained", slug: "rag-explained", status: "published", level: "intermediate", summary: "Follow ingestion, embeddings, retrieval, reranking, citations, and evaluation through a worked example.", aliases: ["retrieval augmented generation", "embeddings", "vector search", "BM25", "hybrid search", "chunking", "reranking", "fine-tuning"], prerequisites: ["ai:ai-llm-foundations", "ai:tokens-context-prompting"], related: ["ai:run-first-local-model", "ai:local-ai-hardware"] },
    ],
  },
];
